import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();
const checkMode = process.argv.includes('--check');
const sourcePath = path.join(repoRoot, 'src/features/ai-assistant/config/aiPromptTemplates.md');
const outputPath = path.join(
  repoRoot,
  'src/features/ai-assistant/config/aiPromptTemplates.generated.ts',
);

const source = fs.readFileSync(sourcePath, 'utf8').replace(/\r\n/g, '\n');

const REQUIRED_PROMPT_SECTIONS = [
  'generation',
  'inspection.en',
  'inspection.zh-Hant',
  'conversation.en',
  'conversation.zh-Hant',
];
const REQUIRED_SECTION_PLACEHOLDERS = {
  generation: ['__ROBOT_CONTEXT__', '__MOTOR_LIBRARY_CONTEXT__'],
  'inspection.en': ['__CRITERIA_DESCRIPTION__', '__INSPECTION_NOTES__', '__LANGUAGE_INSTRUCTION__'],
  'inspection.zh-Hant': ['__CRITERIA_DESCRIPTION__', '__INSPECTION_NOTES__', '__LANGUAGE_INSTRUCTION__'],
  'conversation.en': [
    '__CONVERSATION_MODE__',
    '__CONVERSATION_CONTEXT__',
    '__CONVERSATION_HISTORY__',
    '__LANGUAGE_INSTRUCTION__',
  ],
  'conversation.zh-Hant': [
    '__CONVERSATION_MODE__',
    '__CONVERSATION_CONTEXT__',
    '__CONVERSATION_HISTORY__',
    '__LANGUAGE_INSTRUCTION__',
  ],
};

// Accept LF or CRLF so Windows editors do not break section parsing.
const sectionPattern = /<!-- PROMPT: ([^\r\n]+?) -->\r?\n([\s\S]*?)\r?\n<!-- \/PROMPT -->/g;
const promptSections = new Map();

for (const match of source.matchAll(sectionPattern)) {
  const [, id, content] = match;
  const trimmedId = id.trim();
  if (promptSections.has(trimmedId)) {
    throw new Error(`Duplicate prompt section "${trimmedId}" found in ${sourcePath}`);
  }

  promptSections.set(trimmedId, content.trim());
}

for (const requiredId of REQUIRED_PROMPT_SECTIONS) {
  if (!promptSections.has(requiredId)) {
    throw new Error(`Prompt section "${requiredId}" not found in ${sourcePath}`);
  }
}

const extractPrompt = (id) => {
  const prompt = promptSections.get(id);
  if (!prompt) {
    throw new Error(`Prompt section "${id}" not found in ${sourcePath}`);
  }

  for (const placeholder of REQUIRED_SECTION_PLACEHOLDERS[id] || []) {
    if (!prompt.includes(placeholder)) {
      throw new Error(`Prompt section "${id}" is missing required placeholder ${placeholder}`);
    }
  }

  return prompt;
};

const generatedModule = `// Generated from aiPromptTemplates.md by scripts/generate/generate_ai_prompt_templates.mjs.
// Do not edit this file directly.

export const AI_PROMPT_TEMPLATES = {
  generation: ${JSON.stringify(extractPrompt('generation'))},
  inspection: {
    en: ${JSON.stringify(extractPrompt('inspection.en'))},
    'zh-Hant': ${JSON.stringify(extractPrompt('inspection.zh-Hant'))}
  },
  conversation: {
    en: ${JSON.stringify(extractPrompt('conversation.en'))},
    'zh-Hant': ${JSON.stringify(extractPrompt('conversation.zh-Hant'))}
  }
} as const;
`;

if (checkMode) {
  const currentOutput = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : '';
  if (currentOutput !== generatedModule) {
    console.error(`Generated prompt templates are stale: ${outputPath}`);
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(outputPath, generatedModule);
}
